import { MiningUpgrade, MarketNews } from './types';

export const INITIAL_UPGRADES: MiningUpgrade[] = [
  // GPUs & ASICs
  {
    id: 'gpu_gtx1060',
    name: 'GTX 1060 Vintage',
    type: 'gpu',
    level: 0,
    maxLevel: 25,
    baseCost: 15,
    cost: 15,
    costMultiplier: 1.15,
    description: 'A modest starting GPU. Reliable, but low hashrate.',
    icon: 'Cpu',
    multiplier: 0.15, // +0.15 MH/s
    watts: 20,
    heat: 1.2,
  },
  {
    id: 'gpu_rx6800',
    name: 'RX 6800 Gaming Dual',
    type: 'gpu',
    level: 0,
    maxLevel: 20,
    baseCost: 85,
    cost: 85,
    costMultiplier: 1.18,
    description: 'A solid discrete card with decent memory bandwidth.',
    icon: 'Cpu',
    multiplier: 0.85, // +0.85 MH/s
    watts: 55,
    heat: 2.1,
  },
  {
    id: 'gpu_rtx4090',
    name: 'RTX 4090 Devastator',
    type: 'gpu',
    level: 0,
    maxLevel: 15,
    baseCost: 450,
    cost: 450,
    costMultiplier: 1.22,
    description: 'High-end gaming monster. Perfect for blazing high hashes.',
    icon: 'Zap',
    multiplier: 4.80, // +4.80 MH/s
    watts: 180,
    heat: 5.4,
  },
  {
    id: 'gpu_asic_vault',
    name: 'Ares ASIC Vault Miner',
    type: 'gpu',
    level: 0,
    maxLevel: 10,
    baseCost: 2200,
    cost: 2200,
    costMultiplier: 1.28,
    description: 'A dedicated industrial ASIC miner designed purely for cryptographic tasks.',
    icon: 'HardDrive',
    multiplier: 26.5, // +26.5 MH/s
    watts: 550,
    heat: 14.5,
  },
  {
    id: 'gpu_quantum_rig',
    name: 'Quantum Core Cluster',
    type: 'gpu',
    level: 0,
    maxLevel: 5,
    baseCost: 12500,
    cost: 12500,
    costMultiplier: 1.35,
    description: 'Entangled cubit array executing mathematical hashes at light speed.',
    icon: 'Server',
    multiplier: 185.0, // +185 MH/s
    watts: 1800,
    heat: 45.0,
  },

  // Cooling Systems
  {
    id: 'cool_stock',
    name: 'Stock Fan Exhaust',
    type: 'cooling',
    level: 1, // Mine starts with Level 1 of standard cooling
    maxLevel: 15,
    baseCost: 10,
    cost: 10,
    costMultiplier: 1.14,
    description: 'Basic air cooling. Tempers the starting rig under lighter loads.',
    icon: 'Wind',
    multiplier: -1.5, // cools 1.5 deg/sec (baseline)
    watts: 5,
    heat: 0,
  },
  {
    id: 'cool_rgb_liquid',
    name: 'RGB Dual Liquid Loop',
    type: 'cooling',
    level: 0,
    maxLevel: 15,
    baseCost: 75,
    cost: 75,
    costMultiplier: 1.16,
    description: 'Premium liquid piping with bright lights. Lowers temps effectively.',
    icon: 'Droplet',
    multiplier: -4.5, // cools 4.5 deg/sec
    watts: 15,
    heat: 0,
  },
  {
    id: 'cool_industrial',
    name: 'Chilled Air Intake Conduit',
    type: 'cooling',
    level: 0,
    maxLevel: 10,
    baseCost: 380,
    cost: 380,
    costMultiplier: 1.20,
    description: 'Sucks cold external air through a specialized compressor.',
    icon: 'Wind',
    multiplier: -15.0, // cools 15.0 deg/sec
    watts: 85,
    heat: 0,
  },
  {
    id: 'cool_nitrogen',
    name: 'Liquid Nitrogen Siphon',
    type: 'cooling',
    level: 0,
    maxLevel: 8,
    baseCost: 2400,
    cost: 2400,
    costMultiplier: 1.26,
    description: 'Dispenses pure liquid nitrogen to frost down heavy ASIC blocks.',
    icon: 'Snowflake',
    multiplier: -65.0, // cools 65.0 deg/sec
    watts: 250,
    heat: 0,
  },

  // Power Optimizers
  {
    id: 'power_smart_plug',
    name: 'Smart Wall Meter',
    type: 'power',
    level: 0,
    maxLevel: 10,
    baseCost: 25,
    cost: 25,
    costMultiplier: 1.15,
    description: 'Minimizes power loss. Reduces total rig power draw by 4% per level.',
    icon: 'PlugToggleLeft',
    multiplier: 0.04,
    watts: 1,
    heat: 0,
  },
  {
    id: 'power_solar_array',
    name: 'Rooftop Photovoltaics',
    type: 'power',
    level: 0,
    maxLevel: 8,
    baseCost: 180,
    cost: 180,
    costMultiplier: 1.20,
    description: 'Harvest solar rays to bypass utility grid taxes. Cuts power draw by 8% per level.',
    icon: 'Sun',
    multiplier: 0.08,
    watts: 0,
    heat: 0,
  },
  {
    id: 'power_hydro_turbine',
    name: 'Micro-Hydro Turbine',
    type: 'power',
    level: 0,
    maxLevel: 5,
    baseCost: 1500,
    cost: 1500,
    costMultiplier: 1.25,
    description: 'Infinite local stream power to supply continuous voltage. Saves 15% wattage load per level.',
    icon: 'Waves',
    multiplier: 0.15,
    watts: 0,
    heat: 0,
  },
  {
    id: 'power_fusion',
    name: 'Stellarator Fusion Reactor',
    type: 'power',
    level: 0,
    maxLevel: 3,
    baseCost: 16000,
    cost: 16000,
    costMultiplier: 1.40,
    description: 'Generates self-sustaining plasma core. Shrinks total power billing to near zero (25% per level).',
    icon: 'Flame',
    multiplier: 0.25,
    watts: 0,
    heat: 0,
  },

  // Boosters and Utilities
  {
    id: 'boost_manual',
    name: 'GPU Copper Hotplates',
    type: 'booster',
    level: 0,
    maxLevel: 10,
    baseCost: 10,
    cost: 10,
    costMultiplier: 1.12,
    description: 'Improves active touch conduct. Elevates manual touch mining payout by +100% per level.',
    icon: 'Fingerprint',
    multiplier: 1.0, // +1x to base clicking revenue
    watts: 0,
    heat: 0.1,
  },
  {
    id: 'boost_autoclick',
    name: 'Chronos Payout Scheduler',
    type: 'booster',
    level: 0,
    maxLevel: 5,
    baseCost: 95,
    cost: 95,
    costMultiplier: 1.25,
    description: 'An AI scheduler mimicking clicks. Automates clicking 2 times per second.',
    icon: 'ZapSpeed',
    multiplier: 2, // clicks per second
    watts: 12,
    heat: 0.5,
  },
  {
    id: 'boost_overvolt',
    name: 'Silicon Injector Volts',
    type: 'booster',
    level: 0,
    maxLevel: 5,
    baseCost: 650,
    cost: 650,
    costMultiplier: 1.30,
    description: 'Overvolts core processors, increasing hashrate by +40% per level, but draws +30% more power.',
    icon: 'Gauge',
    multiplier: 0.40, // +40% hashrate
    watts: 1.30, // +30% power scalar
    heat: 2.5,
  },
];

export const NEWS_TEMPLATES: MarketNews[] = [
  {
    id: 'news_1',
    headline: 'Standard Hashrates Surge World-Wide; Blockchain Difficulty Holds Flat',
    impactType: 'bullish',
    impactPercent: 12.5,
    source: 'CoinPedia',
    time: '2m keys ago',
  },
  {
    id: 'news_2',
    headline: 'Major Central Bank declares HashCoin as fully legal digital reserve asset',
    impactType: 'bullish',
    impactPercent: 24.0,
    source: 'Reuters Crypto',
    time: '5m keys ago',
  },
  {
    id: 'news_3',
    headline: 'Quantum chip cooling fire triggers temporary market concerns',
    impactType: 'bearish',
    impactPercent: -15.2,
    source: 'Silicon Watch',
    time: '8m keys ago',
  },
  {
    id: 'news_4',
    headline: 'Decentralized exchanges declare record-breaking $20B HashCoin trading volumes',
    impactType: 'bullish',
    impactPercent: 18.2,
    source: 'DeFi Pulse',
    time: '12m keys ago',
  },
  {
    id: 'news_5',
    headline: 'Cyber Security Agency issues threat warning on minor pool malware',
    impactType: 'bearish',
    impactPercent: -9.4,
    source: 'CyberDefense',
    time: '18m keys ago',
  },
  {
    id: 'news_6',
    headline: 'Tech Billionaire changes profile picture to HashCoin lightning bolt logo',
    impactType: 'bullish',
    impactPercent: 35.5,
    source: 'AlphaTicker',
    time: 'Just Now',
  },
  {
    id: 'news_7',
    headline: 'Renewable energy coalition demands heavy regulations on standard miners',
    impactType: 'bearish',
    impactPercent: -19.5,
    source: 'GreenWeb',
    time: 'Just Now',
  },
  {
    id: 'news_8',
    headline: 'HashCoin miners set new block confirmation record; transfer speeds peak',
    impactType: 'bullish',
    impactPercent: 8.8,
    source: 'BlockExplorer',
    time: 'Just Now',
  },
];
